name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  download-libddwaf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install --ignore-scripts
      - run: node scripts/setup
      - uses: actions/upload-artifact@v4
        with:
          name: libddwaf
          path: libddwaf/**/*

  build:
    needs: download-libddwaf
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      cache: true
      napi: true
      package-manager: 'npm'
      postbuild: 'node scripts/postbuild && npm ci && npm test'
      skip: 'linux-arm,linux-ia32'
      target-name: 'appsec'
      min-node-version: 16

  static-checks:
    strategy:
      matrix:
        run:
          - lint
          - licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run ${{ matrix.run }}

  cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install cpplint
      - run: cpplint --linelength=120 --recursive ./src
