name: Build and release

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]


env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  LIBDDWAF_VERSION: 1.0.8

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint

  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm run licenses

  build-native:
    strategy:
      matrix:
        target:
          - name: macos
            os: macos-latest
            artifact: darwin-x64-unknown
          - name: windows 64 bits # - TODO: windows support when we have a static lib
            os: windows-2016
            artifact: win32-x64-unknown
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci --ignore-scripts
      - run: node scripts/setup.js
      - run: npm run build-test-bundle
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.tgz

  cross-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # TODO: musl x arm support
          # TODO: arm v7 (need upstream builds)
          - dockerfile: arm.Dockerfile
            from: arm64v8/node:14@sha256:d33aee525aab1318a8074bba102d9c55bb82d30454ef233acab0aca1d3cd6c97
            libc: glibc
            arch: arm64
            artifact: linux-arm64-glibc
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci --ignore-scripts
      - run: node scripts/setup.js
        env:
          PLATFORM: 'linux'
          LIBC: ${{ matrix.target.libc }}
          ARCH: ${{ matrix.target.arch }}
      - run: docker build -t build -f ./docker/${{ matrix.target.dockerfile }} --build-arg BUILD_ARG=${{ matrix.target.from }} --platform linux/${{ matrix.target.arch }} .
      - run: docker run --name builder --platform linux/${{ matrix.target.arch }} build
      - run: docker cp builder:/build/${{ matrix.target.artifact }}.tgz .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.tgz

  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - dockerfile: glibc.Dockerfile
            libc: glibc
            artifact: linux-x64-glibc
          - dockerfile: musl.Dockerfile
            libc: musl
            artifact: linux-x64-musl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci --ignore-scripts
      - run: node scripts/setup.js
        env:
          PLATFORM: 'linux'
          LIBC: ${{ matrix.target.libc }}
      - run: docker build -t build -f ./docker/${{ matrix.target.dockerfile }} .
      - run: docker run --name builder build
      - run: docker cp builder:/build/${{ matrix.target.artifact }}.tgz .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}.tgz

  bundle:
    needs: ['build-native', 'build-docker', 'cross-build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - run: mkdir -p vendor
      - run: mv artifacts/*/*.tgz vendor/
      - run: npm pack .
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: datadog-native-appsec-*.tgz
      - uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: vendor

  tests-release-native:
    needs: ['bundle']
    strategy:
      matrix:
        target:
          - name: macos
            os: macos-latest
            artifact: darwin-x64-unknown
          - name: windows 64 bits # - TODO: windows support when we have a static lib
            os: windows-2016
            artifact: win32-x64-unknown
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/download-artifact@v2
        with:
          name: release
      - run: node scripts/rename.js
      - run: npm i -S datadog-native-appsec-0.0.0.tgz
      - run: npm t

  tests-release-docker:
    needs: ['bundle']
    strategy:
      matrix:
        target:
          - node:14@sha256:4164d987bfceb62b17db4938d535dd31fc50d6ee0b4e00ac7a774f82af408d48
          - node:14-alpine@sha256:8c94a0291133e16b92be5c667e0bc35930940dfa7be544fb142e25f8e4510a45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
      - run: docker build -t test -f ./docker/test.Dockerfile --build-arg BASE_IMAGE=${{ matrix.target }} .
      - run: docker run test

  tests-release-cross-build:
    needs: ['bundle']
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello'


  all-good:
    needs: [ tests-release-native,  tests-release-native, lint, licenses]
    runs-on: ubuntu-latest
    steps:
      - run: echo '🚀🚀🚀🚀🚀'
